var searchData=
[
  ['name_0',['A Cliff Note on the Chops Name',['../md_cliff__notes.html',1,'']]],
  ['net_20ip_1',['Class and functions useful with the Chops Net IP',['../group__net__ip__component__module.html',1,'']]],
  ['net_20ip_20detailed_20overview_2',['Chops Net IP Detailed Overview',['../index.html',1,'']]],
  ['net_20ip_20faq_3',['Chops Net IP FAQ',['../md_faq.html',1,'']]],
  ['net_20ip_20library_4',['Net IP library',['../group__net__ip__module.html',1,'Classes and functions for the Chops Net IP library.'],['../group__example__module.html',1,'Example code for Chops Net IP library.']]],
  ['net_20ip_20release_20status_5',['Chops Net IP Release Status',['../md_release.html',1,'']]],
  ['net_20ip_20test_6',['Contents of Chops Net IP Test',['../md__2github_2workspace_2test_2README.html',1,'']]],
  ['net_5fentity_7',['net_entity',['../classchops_1_1net_1_1net__entity.html',1,'chops::net::net_entity'],['../classchops_1_1net_1_1net__entity.html#ab308e9fdec2c56ad8ff61e7716a92003',1,'chops::net::net_entity::net_entity()=default'],['../classchops_1_1net_1_1net__entity.html#ae21683b3a1ff2f6366fcb308bf3cda8f',1,'chops::net::net_entity::net_entity(const std::shared_ptr&lt; ET &gt; &amp;p) noexcept']]],
  ['net_5fentity_2ehpp_8',['net_entity.hpp',['../net__entity_8hpp.html',1,'']]],
  ['net_5fentity_5fcommon_9',['net_entity_common',['../classchops_1_1net_1_1detail_1_1net__entity__common.html',1,'chops::net::detail']]],
  ['net_5fentity_5fcommon_2ehpp_10',['net_entity_common.hpp',['../net__entity__common_8hpp.html',1,'']]],
  ['net_5fentity_5fcommon_3c_20chops_3a_3anet_3a_3adetail_3a_3atcp_5fio_20_3e_11',['net_entity_common&lt; chops::net::detail::tcp_io &gt;',['../classchops_1_1net_1_1detail_1_1net__entity__common.html',1,'chops::net::detail']]],
  ['net_5fentity_5fcommon_3c_20chops_3a_3anet_3a_3adetail_3a_3audp_5fentity_5fio_20_3e_12',['net_entity_common&lt; chops::net::detail::udp_entity_io &gt;',['../classchops_1_1net_1_1detail_1_1net__entity__common.html',1,'chops::net::detail']]],
  ['net_5fentity_5fcommon_5ftest_2ecpp_13',['net_entity_common_test.cpp',['../net__entity__common__test_8cpp.html',1,'']]],
  ['net_5fentity_5fmock_14',['net_entity_mock',['../structchops_1_1test_1_1net__entity__mock.html',1,'chops::test']]],
  ['net_5fentity_5ftest_2ecpp_15',['net_entity_test.cpp',['../net__entity__test_8cpp.html',1,'']]],
  ['net_5fip_16',['net_ip',['../classchops_1_1net_1_1net__ip.html',1,'chops::net::net_ip'],['../classchops_1_1net_1_1net__ip.html#a5479f7f867e1b7a3bd673d1fb9456e71',1,'chops::net::net_ip::net_ip()']]],
  ['net_5fip_2ehpp_17',['net_ip.hpp',['../net__ip_8hpp.html',1,'']]],
  ['net_5fip_5ferr_5fcategory_18',['net_ip_err_category',['../structchops_1_1net_1_1detail_1_1net__ip__err__category.html',1,'chops::net::detail']]],
  ['net_5fip_5ferror_2ehpp_19',['net_ip_error.hpp',['../net__ip__error_8hpp.html',1,'']]],
  ['net_5fip_5ferror_5ftest_2ecpp_20',['net_ip_error_test.cpp',['../net__ip__error__test_8cpp.html',1,'']]],
  ['net_5fip_5fexception_21',['net_ip_exception',['../classchops_1_1net_1_1net__ip__exception.html',1,'chops::net']]],
  ['net_5fip_5ftest_2ecpp_22',['net_ip_test.cpp',['../net__ip__test_8cpp.html',1,'']]],
  ['networking_20standardization_23',['Asio and C++ Networking Standardization',['../md_lib__comparison.html#autotoc_md43',1,'']]],
  ['next_20steps_20todo_20s_20problems_20and_20constraints_3a_24',['Next Steps ToDo s Problems and Constraints:',['../md_release.html#autotoc_md60',1,'Next Steps, ToDo&apos;s, Problems, and Constraints:'],['../md_release.html#autotoc_md64',1,'Next Steps, ToDo&apos;s, Problems, and Constraints:']]],
  ['no_5fstart_5fio_5fstate_5fchg_25',['no_start_io_state_chg',['../structno__start__io__state__chg.html',1,'']]],
  ['note_20on_20the_20chops_20name_26',['A Cliff Note on the Chops Name',['../md_cliff__notes.html',1,'']]],
  ['notes_27',['Notes',['../md_release.html#autotoc_md63',1,'Notes'],['../md_release.html#autotoc_md67',1,'Notes']]],
  ['notify_5fme_28',['notify_me',['../structnotify__me.html',1,'']]]
];
